# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(526, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(330, 80, 181, 171))
        self.treeWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.treeWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setWordWrap(False)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 70, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 526, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "连接"))
        self.pushButton_2.setText(_translate("MainWindow", "断开"))
        self.pushButton.setText(_translate("MainWindow", "移动"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "项目名"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "信息"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "节点名"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("MainWindow", "OpenFlow 2"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "负载"))
        self.treeWidget.topLevelItem(1).setText(1, _translate("MainWindow", "2.1"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "连接设备"))
        self.treeWidget.topLevelItem(2).setText(1, _translate("MainWindow", "3台"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "h1"))
        self.treeWidget.topLevelItem(2).child(0).setText(1, _translate("MainWindow", "↑ 20KB/s ↓11KB/S"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "h2"))
        self.treeWidget.topLevelItem(2).child(1).setText(1, _translate("MainWindow", "↑ 10KB/s ↓21KB/S"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "h3"))
        self.treeWidget.topLevelItem(2).child(2).setText(1, _translate("MainWindow", "↑ 11KB/s ↓53KB/S"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "已禁用设备"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "h4"))
        self.treeWidget.topLevelItem(3).child(0).setText(1, _translate("MainWindow", "已禁用"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "连接到的交换机"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "OpenFlow 1"))
        self.treeWidget.topLevelItem(4).child(0).setText(1, _translate("MainWindow", "时延 10ms"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)

